const CatalogProduct = [
    {
        photo: '../images/tovarFoto.png',
        title: 'Colombia Supremo',
        description: 'Свежеобжаренный кофе - описание товара, вкус, аромат',
        vaga: [150, 250, 500, 1000],
        price: [250, 350, 500, 750],
        countVidgukiv: 32,
        grade: 4,
        kislinka: 8,
        gorchinka: 7,
        nasishenost: 2,
        geografia:"Африка",
        processing:"Cухая",
        spesial:"Популярное",
        vid_coffee:"Арабика",
        projarka:3,
        discaunt: true


    },
     {
        photo: '../images/tovarFoto.png',
        title: 'Colombia Supremo1',
        description: 'Свежеобжаренный кофе - описание товара, вкус, аромат',
        vaga: [150, 250, 500, 3000],
        price: [250, 350, 500, 2000],
        countVidgukiv: 32,
        grade: 2,
        kislinka: 9,
        gorchinka: 10,
        nasishenost: 10,
        geografia:"Африка",
        processing:"Cухая",
        spesial:"Популярное",
        vid_coffee:"Арабика",
        projarka:5,
        pribor:"Turka",
        discaunt: true
    }, 
    {
        photo: '../images/tovarFoto.png',
        title: 'Colombia Supremo2',
        description: 'Свежеобжаренный кофе - описание товара, вкус, аромат',
        vaga: [150, 250, 500, 2000],
        price: [250, 350, 500, 1000],
        countVidgukiv: 32,
        grade: 5,
        kislinka: 8,
        gorchinka: 7,
        nasishenost: 4,
        geografia:"Уганда",
        projarka:4,
        processing:"Мытая",
        spesial:"Популярное",
        vid_coffee:"Робуста",
        pribor:"Moka",
        discaunt: true
    },
    {
        photo: '../images/tovarFoto.png',
        title: 'Colombia Supremo',
        description: 'Свежеобжаренный кофе - описание товара, вкус, аромат',
        vaga: [150, 250, 500, 1000],
        price: [250, 350, 500, 750],
        countVidgukiv: 32,
        grade: 4,
        kislinka: 8,
        gorchinka: 7,
        nasishenost: 2,
        geografia:"Африка",
        processing:"Cухая",
        spesial:"Популярное",
        vid_coffee:"Арабика",
        pribor:"Press",
        projarka:5,
        pribor:"Moka",
        discaunt: true


    },
     {
        photo: '../images/tovarFoto.png',
        title: 'Colombia Supremo1',
        description: 'Свежеобжаренный кофе - описание товара, вкус, аромат',
        vaga: [150, 250, 500, 3000],
        price: [250, 350, 500, 2000],
        countVidgukiv: 32,
        grade: 2,
        kislinka: 9,
        gorchinka: 10,
        nasishenost: 10,
        geografia:"Эфиопия",
        processing:"Cухая",
        spesial:"Популярное",
        vid_coffee:"Арабика",
        projarka:5,
        discaunt: false
    }, 
    {
        photo: '../images/tovarFoto.png',
        title: 'Colombia Supremo2',
        description: 'Свежеобжаренный кофе - описание товара, вкус, аромат',
        vaga: [150, 250, 500, 2000],
        price: [250, 350, 500, 1000],
        countVidgukiv: 40,
        grade: 5,
        kislinka: 8,
        gorchinka: 7,
        nasishenost: 4,
        geografia:"Уганда",
        processing:"Мытая",
        spesial:"Популярное",
        vid_coffee:"Робуста",
        projarka:3,
        discaunt:  false
    },{
        photo: '../images/tovarFoto.png',
        title: 'Colombia Supremo',
        description: 'Свежеобжаренный кофе - описание товара, вкус, аромат',
        vaga: [150, 250, 500, 1000],
        price: [250, 350, 500, 750],
        countVidgukiv: 32,
        grade: 4,
        kislinka: 8,
        gorchinka: 7,
        nasishenost: 2,
        geografia:"Африка",
        processing:"Cухая",
        spesial:"Популярное",
        vid_coffee:"Арабика",
        projarka:3,
        discaunt:  false


    },
     {
        photo: '../images/tovarFoto.png',
        title: 'Colombia Supremo1',
        description: 'Свежеобжаренный кофе - описание товара, вкус, аромат',
        vaga: [150, 250, 500, 3000],
        price: [250, 350, 500, 2000],
        countVidgukiv: 32,
        grade: 2,
        kislinka: 9,
        gorchinka: 10,
        nasishenost: 10,
        geografia:"Африка",
        processing:"Cухая",
        spesial:"Популярное",
        vid_coffee:"Арабика",
        projarka:3,
        discaunt:  false
    }, 
    {
        photo: '../images/tovarFoto.png',
        title: 'Colombia Supremo2',
        description: 'Свежеобжаренный кофе - описание товара, вкус, аромат',
        vaga: [150, 250, 500, 2000],
        price: [250, 350, 500, 1000],
        countVidgukiv: 32,
        grade: 5,
        kislinka: 8,
        gorchinka: 7,
        nasishenost: 4,
        geografia:"Уганда",
        processing:"Мытая",
        spesial:"Ваш выбор",
        vid_coffee:"Робуста",
        projarka:3,
        discaunt:  false
    },{
        photo: '../images/tovarFoto.png',
        title: 'Colombia Supremo',
        description: 'Свежеобжаренный кофе - описание товара, вкус, аромат',
        vaga: [150, 250, 500, 1000],
        price: [250, 350, 500, 750],
        countVidgukiv: 32,
        grade: 4,
        kislinka: 8,
        gorchinka: 7,
        nasishenost: 2,
        geografia:"Африка",
        processing:"Cухая",
        spesial:"Ваш выбор",
        vid_coffee:"Арабика",
        projarka:3,
        discaunt:  false


    },
     {
        photo: '../images/tovarFoto.png',
        title: 'Colombia Supremo1',
        description: 'Свежеобжаренный кофе - описание товара, вкус, аромат',
        vaga: [150, 250, 500, 3000],
        price: [250, 350, 500, 2000],
        countVidgukiv: 32,
        grade: 2,
        kislinka: 9,
        gorchinka: 10,
        nasishenost: 10,
        geografia:"Африка",
        processing:"Cухая",
        spesial:"Новый урожай",
        vid_coffee:"Арабика",
        projarka:3,
        discaunt:  false
    }, 
    {
        photo: '../images/tovarFoto.png',
        title: 'Colombia Supremo2',
        description: 'Свежеобжаренный кофе - описание товара, вкус, аромат',
        vaga: [150, 250, 500, 2000],
        price: [250, 350, 500, 1000],
        countVidgukiv: 32,
        grade: 5,
        kislinka: 8,
        gorchinka: 7,
        nasishenost: 4,
        geografia:"Уганда",
        processing:"Мытая",
        spesial:"Новый урожай",
        vid_coffee:"Робуста",
        projarka:3,
        pribor:"Avtomat",
        discaunt:  false
    }
];
export default CatalogProduct;